name: pet_body_health
description: "pet care"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dropdown_button2: ^2.3.9
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12
  icons_launcher: ^3.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

icons_launcher:
  image_path: "assets/icons/logo.png"
  platforms:
    android:
      enable: true


flutter:
  uses-material-design: true
  assets:
    - assets/icons/bluetooth-off.png
    - assets/icons/bluetooth-off-1.png
    - assets/icons/bluetooth-off-2.png
    - assets/icons/bluetooth-off-3.png
    - assets/icons/bluetooth-on.png
    - assets/icons/line-chart.png
    - assets/icons/logo.png